// ==UserScript==
// @name        Achieve
// @namespace   xmods
// @match       https://achieve.hashtag-learning.co.uk/assess/question-page/
// @grant       none
// @version     1.0
// @author      xmods
// @grant       GM_setValue
// @grant       GM_getValue
// @grant       GM_deleteValue
// ==/UserScript==

const data = {
	// Analysis (web)
	[`<p>Wagtail Dog Walking Services are designing a new website. The site should have a link from the home page to a Prices page listing the different services available. Customers should be able to send a message to Wagtail by clicking a button on the Prices page. The home page will show photographs of customer dogs being walked and customers will have the option to purchase photos by adding them to a virtual basket. In order to purchase photographs, users must be logged in to the site, and there should be a sign up / login button at the top of every page.</p><p>Which of the following are <strong>end user requirements</strong> for this website?</p><ol><li>Login button at the top of every page.</li><li>Link on the home page a prices page</li><li>Send a message to Wagtail</li><li>Sign up / login</li></ol>`]: `button_2`,
	[`<p>Wagtail Dog Walking Services are designing a new website. The site should have a link from the home page to a Booking page which lets customers book their dog in for a walk. The home page will show photographs of customer dogs being walked, and users will be able to 'like' individual photos by clicking a small heart icon.</p><p>Which of the following are <strong>end user requirements</strong> for this website?</p><ol><li>Like dog photo</li><li>Link on home page to booking page</li><li>Link to contact page</li><li>Book dog walk</li></ol>`]: `button_1`,
	[`<p>Duncastle United Football Club are designing a new website so that supporters can find out information about the team, including statistics and photos of every player. The website should have a sign up / login button available on every page. It will access and store data in a database with User and Player tables.</p><p>Which of the following are <strong>functional requirements</strong> for this website?</p><ol><li>Player table: View statistics</li><li>Student table: View test scores</li><li>Player table: Check out and pay</li><li>User table: Sign up</li></ol>`]: `button_1`,
	[`<p>Wagtail Dog Walking Services are designing a new website. The site should have a link from the home page to a Prices page listing the different services available. Customers should be able to login to the site to see photographs of their dog being walked. There should be a sign up / login button at the top of every page. The site will be required to access and store data in a database with User and Dog tables.</p><p>Which of the following are <strong>functional requirements</strong> for this website?</p><ol><li>Login button at the top of every page.</li><li>View dog photographs</li><li>Dog table: Get photographs</li><li>User table: Sign up</li></ol>`]: `button_3`,
	[`<p>Wagtail Dog Walking Services are designing a new website. The site should have a link from the home page to a Prices page listing the different services available. Customers should be able to send a message to Wagtail by clicking a button on the Prices page. The home page will show photographs of customer dogs being walked and customers will have the option to purchase photos by adding them to a virtual basket. In order to purchase photographs, users must be logged in to the site, and there should be a sign up / login button at the top of every page.</p><p>Which of the following are <strong>functional requirements</strong> for this website?</p><ol><li>Login button at the top of every page.</li><li>Link on the home page a prices page</li><li>Send a message to Wagtail</li><li>Sign up / login</li></ol>`]: `button_1`,
	[`<p>Duncastle United Football Club are designing a new website so that supporters can find out information about the team.  There should be links from the home page to a results page, the league table page and a squad page. Every page should have a link to the club shop where supporters can be purchase replica kits and other items by adding them to a virtual basket and then visiting the online checkout.</p><p>Which of the following are <strong>functional requirements</strong> for this website?</p><ol><li>Links from home page to national team web page</li><li>Links from home page to results page</li><li>Links from every page to club shop</li><li>Purchase replica kit</li></ol>`]: `button_3`,
	[`<p>Soundz Music are designing a website to sell music downloads for upcoming artists. Users visiting the website can hear 30 second samples of each song, and can leave artist reviews.</p><p>Which of the following would <strong>NOT</strong> be an functional requirement for this website?</p>`]: `button_1`,
	[`<p>Duncastle United Football Club are designing a new website so that supporters can find out information about the team. Supporters should be able to search for player by squad number and send a player a message when viewing their page. The website should have a competition page which lets supporters submit their prediction for the result of the next Duncastle United match.</p><p>Which of the following are <strong>end user requirements</strong> for this website?</p><ol><li>Delete user from user table</li><li>Update player table</li><li>Send player a message</li><li>Submit predicition of next match result</li></ol>`]: `button_4`,
	[`<p>Soundz Music are designing a website to sell music downloads for upcoming artists. Users visiting the website can hear 30 second samples of each song, and can leave artist reviews.</p><p>Which of the following might be an end-user requirement for this website?</p>`]: `button_2`,
	[`<p>Duncastle United Football Club are designing a new website so that supporters can find out information about the team. Each player in the squad will have a page with a photo and statistics. Every page should have a link to the club shop where supporters can be purchase replica kits and other items by adding them to a virtual basket and then visiting the online checkout.</p><p>Which of the following are <strong>end user requirements</strong> for this website?</p><ol><li>View player photo</li><li>Link from home page to Duncastle United rivals</li><li>Add product to virtual basket</li><li>Links from home page to squad page</li></ol>`]: `button_2`,

	// Design (web)
	[`<p>Catwalk Clothing Store have designed a website with the following pages:</p><ul><li>Home</li><li>Sale</li><li>T-shirts</li><li>Trainers</li><li>Contact</li></ul><p>Additional information:</p><ul><li>There should be links from the Home page to the T-shirts, Trainers and Contact pages</li><li>The T-shirts, Trainers and Contact pages should have links back to the Home page</li><li>The T-shirts and Trainers pages should link to the Sale page</li><li>The Sale page should only link to the Home page</li></ul><p>Which of the following correctly shows the navigational structure of the website?</p>`]: `button_1`,
	[`<p>Which of the following statements about MP3 files are true?</p><ol><li>Uncompressed</li><li>Standard for audio CDs</li><li>Lossy compression</li><li>Removes frequencies generally not heard by human ear</li></ol>`]: `button_4`,
	[`A file is made smaller so that it can be streamed more quickly. What is the technique of reducing the file size called?`]: `>compression`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-low-fidelity-prototype-mc-2.png"><br><br><p>What is the web page design shown above known as?</p>`]: `button_3`,
	[`Which graphic file format uses lossy compression and is commonly used to store photographs?`]: `>jpg`,
	[`Which graphic file format has a colour palette of 256 colours and supports animation?`]: `>gif`,
	[`What is the term used to describe the number of pixels in an image?`]: `>resolution`,
	[`Which uncompressed audio format is the standard for audio CDs?`]: `>wav`,
	[`An image can have up to 256 different colours. What is the colour depth of this image?`]: `>8 bits`,
	[`<p>Which of the following statements about GIF files are true?</p><ol><li>Not suitable for photographs</li><li>8 bit colour depth</li><li>Transparency</li><li>Lossy compression</li></ol>`]: `button_1`,
	[`<p>Alexis is producing a website for her own company. Which of the following would <strong>not</strong> comply with the Copyright, Designs and Patents Act (1988)?</p>`]: `button_3`,
	[`<p>Which of the following statements about WAV files are true?</p><ol><li>Uncompressed</li><li>Standard for audio CDs</li><li>Lossy compression</li><li>Removes frequencies generally not heard by human ear</li></ol>`]: `button_1`,
	[`<p>Stephen has downloaded a photograph from another website and has published it on the home page of his own website withoiut seeking permission.</p><p>Which act has Stephen not complied with in publishing the photograph on his own website?</p>`]: `>Copyright, Designs and Patents Act`,
	[`<p>Wagtail Dog Walking Services are designing a new website. The Home page should show Wagtail Dog Walking Services as a heading, followed by 2 rows of 3 photographs of different dogs being walked. A short paragraph describing the business should appear below the photographs. An internal link to Services should be shown at the foot of the page, with an external link to The Kennel Club www.kclub.co.uk shown below that.</p><p>Which of the following would be a suitable wireframe for the Wagtail home page?</p>`]: `button_4`,
	[`<p>Which of the following are the main purposes of Copyright, Designs and Patents Act?</p><ol><li>To limit the number of images and videos on the Internet</li><li>To ensure people are rewarded for their work</li><li>To give the copyright holder protection from their work being copied or stolen</li><li>To maintain a central record of all online media</li></ol>`]: `button_2`,
	[`<p>Which of the following is true.</p><p>The lower the colour depth of an image, it will have:</p>`]: `button_4`,
	[`<p>Which of the following is true.</p><p>The lower the resolution of an image is, it will have:</p>`]: `button_3`,
	[`<p>Which of the following is true.</p><p>The higher the colour depth of an image, it will have:</p>`]: `button_1`,
	[`<p>Lois wants to use an photograph which she has found online on her own web site.</p><p>Which of the following could Lois do in order to comply with the Copyright, Designs and Patents Act?</p><ol><li>Seek permission to use the image from the copyright owner</li><li>Give the photograph a different title so no one can tell</li><li>Claim that she took the photograph herself</li><li>Give credit for the use of the photograph</li></ol>`]: `button_4`,
	[`<p>Which of the following is true.</p><p>The higher the sample rate of a song, it will have:</p>`]: `button_2`,
	[`A compressed song file has lost some of the original data. What kind of compression has been used?`]: `>lossy compression`,
	[`<p>Byte Repairs fix hardware devices including computers, tablets and game consoles. They have produced a website with the following pages:</p><ul><li>Home page</li><li>Information about the company</li><li>Prices</li><li>Tips for repairing devices</li></ul><p>Additional information:</p><ul><li>Each page has a link back to the home page</li><li>The company information page has an external link to a website which provides company reviews</li><li>The page with repair tips has an external link to a YouTube video</li></ul><p>Which of the following correctly shows the navigational structure of the website?</p>`]: `button_2`,
	[`Which audio file format is most suitable for streaming audio?`]: `button_1`,
	[`Which audio file format is uncompressed?`]: `button_2`,
	[`<p>Ki downloads a music track from the Internet and publishes it on one of the pages on her own website.</p><p>Which act has Ki not complied with in publishing the music on her site?</p>`]: `button_3`,
	[`Which graphic file format is <strong>NOT</strong> suitable for storing photographs?`]: `button_3`,
	[`An image has a resolution of 204800. What does this mean?`]: `button_3`,
	[`<p>Which of the following statements about JPEG files are true?</p><ol><li>Lossy compression</li><li>8 bit colour depth</li><li>Support animation</li><li>No transparency</li></ol>`]: `button_3`,
	[`<p>Duncastle United Football Club have designed a website with the following pages:</p><ul><li>Home</li><li>Squad</li><li>Results</li><li>Shop</li></ul><p>Additional information:</p><ul><li>There should be links from the Home page to the Squad and Results pages</li><li>The Squad and Results Pages should have links back to the Home page</li><li>The Shop link should appear on every page</li><li>The Shop page should only link back to the home page</li></ul><p>Which of the following correctly shows the navigational structure of the website?</p>`]: `button_4`,
	[`What is the term used to describe the number of bits used to store the colour for each pixel in an image?`]: `>colour depth`,
	[`<p>Which of the following should <strong>NOT</strong> be included on a wireframe for a website design?</p>`]: `button_4`,
	[`Which graphic file format can have over 16 million colours and a transparent background?`]: `button_2`,
	[`<p>Duncastle United Football Club are redesigning their web site. The About Duncastle United page should have a suitable heading followed by a paragraph summarising the history of the club. A photograph of the club stadium should be displayed next to a paragraph describing it's features and when it was built. At the bottom of the page there should be a photograph of the current manager and captain, and along the top of the page there should be links to 3 other pages on the website: Home, Squad and Shop.</p><p>Which of the following would be a suitable wireframe for the About Duncastle United page?</p>`]: `button_1`,
	[`Which audio format uses lossy compression, removing very high and very low frequencies to reduce the file to around one tenth of its original size?`]: `>mp3`,
	[`<p>Greenway Gardening have designed a website with the following pages:</p><ul><li>Home</li><li>Services</li><li>Tips</li></ul><p>Additional information:</p><ul><li>There should be links from the Home page to the Services and Tips pages</li><li>The Services and Tips pages should have links back to the Home page</li><li>The Home page should have an external link to a video about plants and a video about gardening equipment, both on YouTube</li><li>The Home page shoould have an external link to the Duncastle Garden Centre who agree to provide a link from their site back to the Tips page</li></ul><p>Which of the following correctly shows the navigational structure of the website?</p>`]: `button_3`,
	[`A song is sampled at a sample rate of 48000 Hz. What does this mean?`]: `button_3`,
	[`<p>What is a sketch of a web page that includes actual text and sketches of images and videos known as?</p>`]: `button_1`,
	[`<p>Amena is designing a web page. She begins by producing a wireframe to show a rough layout of the page.</p><p>Next she produces a more detailed sketch of the page to include any actual text and sketches of images.</p><p>What is the name for the second design technique that Amena has used?</p>`]: `>low-level prototype`,
	[`A photograph has a colour depth of 16 bits. What does this mean?`]: `button_2`,
	[`<p>Aaron records a video of his cat and uploads it to his website.</p><p>Why does Aaron not have to worry about infringing the Copyright, Designs and Patents Act?</p>`]: `button_2`,
	[`What is the term used to describe the reduction of a file size so that it requires less storage space?`]: `>compression`,
	[`<p>Which of the following statements about PNG files are true?</p><ol><li>Support animation</li><li>Not suitable for photographs</li><li>Transparency</li><li>24 bit colour depth</li></ol>`]: `button_4`,
	[`<p>Which of the following is true.</p><p>The lower the sample rate of a song, it will have:</p>`]: `button_3`,
	[`Which graphic file format uses lossless compression and supports transparency?`]: `>png`,
	[`<p>Which of the following statements about GIF files are true?</p><ol><li>Lossy compression</li><li>8 bit colour depth</li><li>Support animation</li><li>No transparency</li></ol>`]: `button_2`,
	[`<p>Which of the following statements about JPEG files are true?</p><ol><li>Not suitable for photographs</li><li>Support animation</li><li>24 bit colour depth</li><li>Lossless compression</li></ol>`]: `button_2`,
	[`<p>Which of the following should be included on a wireframe for a website design?</p>`]: `button_3`,
	[`<p>Which of the following show a Low-fidelity Prototype for a web page design?</p>`]: `button_3`,
	[`<p>Which of the following is true.</p><p>The higher the resolution of an image is, it will have:</p>`]: `button_2`,
	[`<p>Wagtail Dog Walking Services have designed a website with the following pages:</p><ul><li>Home</li><li>Prices</li><li>Book</li><li>Breeds</li></ul><p>Additional information:</p><ul><li>There should be links from the Home page to the Prices and Breeds pages</li><li>The Prices and Breeds Pages should have links back to the Home page</li><li>The Prices page should link to the Book page</li><li>The Book page should link back to the Prices page</li><li>The Breed page should have an external link to The Kennel Club but they will not link back to Wagtail Dog Walking</li></ul><p>Which of the following correctly shows the navigational structure of the website?</p>`]: `button_2`,
	[`<p>Which of the following statements about PNG files are true?</p><ol><li>Lossy compression</li><li>Lossless compression</li><li>Transparency</li><li>8 bit colour depth</li></ol>`]: `button_3`,
	[`An image is compressed and none of the original data has been lost. What kind of compression has been applied?`]: `>Lossless compression`,
	[`What is the term used to describe the measure of how many times per second a sound is sampled?`]: `>Sample rate`,
	[`<p>Catwalk Clothing Store are designing a new website. The Home page should show show a link to the Shop page along the top. An image of a t-shirt alongside an image of a pair of trainers should be shown underneath the link followed by the company name in a large font. Information about the company should appear below comany name, and a photograph of the Clothing Retailer of the Year award which the company won recently should appear at the bottom of the page.</p><p>Which of the following would be a suitable wireframe for the Catwalk Clothing home page?</p>`]: `button_2`,

	// Implementation (CSS)
	[`<p>Which of the following is an advantage of internal CSS over external CSS?</p>`]: `button_1`,
	[`<p>Where is internal CSS stored?</p>`]: `button_1`,
	[`<p>Which CSS rule has been applied to the paragraph on the web page shown below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-color-mc-4.png"><br><br>`]: `button_4`,
	[`<p>Which of the following CSS rules will set the background colour of all h1 elements to gold?</p>`]: `button_2`,
	[`<p>What is the CSS property used to align text?</p>`]: `button_4`,
	[`<p>Which CSS rule has been applied to the web page shown below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-background-color-mc-4.png"><br><br>`]: `button_4`,
	[`What is the name of the styling language that is used to define how HTML elements should be displayed?`]: `>css`,
	[`<p>What is the name of the id selector shown in the CSS below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-id-selector-mc-3.png"><br><br>`]: `button_3`,
	[`<p>Andrew writes the following CSS class called intro:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-text-1-css.png"><br><br><p>He uses the intro class to style the following HTML paragraph element:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-text-1-html.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>intro`,
	[`<p>Thomas writes the following CSS rule to set the background colour of all p elements to sky blue.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-background-color-text-2.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>background-color`,
	[`<p>Artur writes the following CSS rule to set the font of all &lt;h1&gt; elements to Calibri size 24.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-font-text-3.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>font-size`,
	[`<p>Sandeep writes the following CSS rule to set the font of all paragraph elements to Helvetica size 12.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-font-text-2.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>font-family`,
	[`<p>Keira writes the following CSS rule to left align all paragraph elements.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-alignment-text-3.png"><br><br><p>Identify the two characters that have been removed.</p>`]: `>{ and }`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-selector-mc-3.png"><br><br><p>Which of the following is a CSS selector used in the code above?</p>`]: `button_4`,
	[`<p>State the CSS selector used in the following code</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-selector-text-1.png"><br><br>`]: `>div`,
	[`<p>Anna writes the following CSS rule to set the text colour of all h2 elements to crimson.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-color-text-3.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>crimson`,
	[`<p>Cora writes the following CSS class:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-mc-1-css.png"><br><br><p>Which of the following correctly applies Cora's CSS class to an HTML div element?</p>`]: `button_4`,
	[`<p>Jamie writes the following CSS rule to set the font of all paragraph elements to Arial size 10.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-font-text-1.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>p`,
	[`<p>Lin writes the following internal CSS class.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-internal-text-1.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>style`,
	[`<p>Eva writes the following CSS rule to set the text colour of all h4 elements to dark green.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-color-text-1.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>h4`,
	[`<p>Which of the following CSS rules will set the font of all h5 elements to Arial, size 12px?</p>`]: `button_1`,
	[`<p>Which of the following CSS rules will set the colour of all h1 elements to blue?</p>`]: `button_4`,
	[`<p>What is the purpose of CSS?</p>`]: `button_3`,
	[`<p>CSS is used to style HTML as shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-mc-3.png"><br><br><p>Which of the following shows the resulting web page?</p>`]: `button_2`,
	[`<p>State the CSS selector used in the following code</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-selector-text-2.png"><br><br>`]: `>intro`,
	[`Which of the following symbols is used in the definition of a CSS class?`]: `button_3`,
	[`<p>Sandeep writes the following CSS rule to set the background colour of all div elements to pale green.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-background-color-text-1.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>div`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-selector-mc-2.png"><br><br><p>Identify two CSS selectors used in the code above?</p>`]: `button_2`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-selector-mc-1.png"><br><br><p>Which of the following is a CSS selector used in the code above?</p>`]: `button_1`,
	[`<p>Which of the following CSS rules will align all h1 elements to the right?</p>`]: `button_1`,
	[`<p>State the CSS selector used in the following code</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-selector-text-3.png"><br><br>`]: `>paragraph`,
	[`<p>Lara wants to write a CSS id selector named body-text.</p><p>Which of the following is the correct way to write the id selector?</p>`]: `button_2`,
	[`<p>Which of the following is an advantage of external CSS?</p>`]: `button_2`,
	[`<p>Magnus writes the following CSS rule to right align all h3 elements.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-alignment-text-1.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>text-align`,
	[`<p>What is the CSS property used to set the background colour?</p>`]: `button_4`,
	[`<p>Which CSS rule has been applied to the h1 heading on the web page shown below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-background-color-mc-5.png"><br><br>`]: `button_3`,
	[`<p>State the type of CSS which has been used below:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-external-mc-2.png"><br><br>`]: `button_3`,
	[`<p>Which of the following CSS rules will set the font of all h1 elements to Verdana , size 20px?</p>`]: `button_3`,
	[`Which of the following symbols is used in the definition of a CSS id?`]: `button_4`,
	[`<p>Tony writes the following CSS class called summary:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-text-2-css.png"><br><br><p>He uses the summary class to style the following HTML div element:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-text-2-html.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>class`,
	[`<p>Which of the following is the correct way to write internal CSS?</p>`]: `button_3`,
	[`<p>How many elements can a CSS id selector style on a single web page?</p>`]: `button_2`,
	[`<p>Faye wants to write a CSS class selector named header-block.</p><p>Which of the following is the correct way to write the class selector?</p>`]: `button_3`,
	[`<p>Which type of CSS has been used below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-internal-mc-2.png"><br><br>`]: `button_2`,
	[`<p>Which of the following CSS rules will set the colour of all div elements to green?</p>`]: `button_3`,
	[`<p>Which CSS rule has been applied to the paragraph on the web page shown below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-alignment-mc-4.png"><br><br>`]: `button_2`,
	[`<p>Which CSS rule has been applied to the h1 heading on the web page shown below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-alignment-mc-5.png"><br><br>`]: `button_3`,
	[`<p>Leigh writes the following CSS id which she names summary:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-id-selector-text-2-css.png"><br><br><p>She uses the summary id to style the following HTML div element:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-id-selector-text-2-html.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>id`,
	[`<p>CSS is used to style HTML as shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-mc-4.png"><br><br><p>Which of the following shows the resulting web page?</p>`]: `button_1`,
	[`<p>Beth writes the following CSS rule to set the background colour of all div elements to orange.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-background-color-text-3.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>orange`,
	[`<p>Leeanne writes the following CSS id:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-id-selector-mc-1-css.png"><br><br><p>Which of the following correctly applies Leeanne's CSS id to an HTML div element?</p>`]: `button_1`,
	[`<p>State the type of CSS which has been used below:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-internal-mc-1.png"><br><br>`]: `button_2`,
	[`<p>What is the name of the class selector shown in the CSS below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-class-selector-mc-5.png"><br><br>`]: `button_1`,
	[`<p>Which of the following CSS rules will set the font of all p elements to Times New Roman, size 8px?</p>`]: `button_2`,
	[`<p>Siobhan writes the following CSS rule to set the text colour of all paragraph elements to dodger blue.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-color-text-2.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>color`,
	[`<p>Which of the following CSS rules will align all &lt;p&gt; elements to the centre?</p>`]: `button_3`,
	[`<p>How many elements can a CSS class selector style on a single web page?</p>`]: `button_4`,
	[`<p>Where is external CSS stored?</p>`]: `button_2`,
	[`<p>Which CSS rule has been applied to the h1 heading on the web page shown below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-color-mc-5.png"><br><br>`]: `button_1`,
	[`<p>Which of the following CSS rules will set the background colour of all div elements to lavender?</p>`]: `button_1`,
	[`<p>Which of the following is an advantage of external CSS over internal CSS?</p>`]: `button_2`,
	[`<p>Which type of CSS has been used below?</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-external-mc-3.png"><br><br>`]: `button_4`,
	[`<p>Which of the following is the correct way to write external CSS?</p>`]: `button_4`,
	[`<p>Patrice writes the following CSS id which he names intro:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-id-selector-text-1-css.png"><br><br><p>He uses the intro id to style the following HTML paragraph element:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-id-selector-text-1-html.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>intro`,
	[`<p>Anya writes the following CSS rule to centrally align all h1 elements.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-css-text-alignment-text-2.png"><br><br><p>Identify the CSS code that has been removed.</p>`]: `>center`,
	[`<p>What is the CSS property used to set the text colour?</p>`]: `button_1`,

	// Implementation (HTML)
	[`<p>The following HTML shows the basic structure of a web page. Identify the HTML tag that has been removed.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-structure-text-3.png"><br><br>`]: `>html`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-hyperlinks-mc-2.png"><br><br><p>Which type of hyperlink is Kennel Club UK?</p>`]: `button_2`,
	[`<p>Which of the following is the HTML tag used to embed the file <strong><i>basketball.mp4</i></strong> on a web page?</p>`]: `button_2`,
	[`<p>Three different HTML heading tags have been used to produce the page shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-heading-text-1-1.png"><br><br><p>The following code was used to create the page.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-heading-text-1-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>h1`,
	[`<p>Name the HTML tag used to display an unordered list on a web page</p>`]: `>ul`,
	[`<p>The web page below makes use of the following HTML tags: &lt;h1&gt; &lt;h4&gt; &lt;p&gt; &lt;a&gt;</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-paragraph-mc-2.png"><br><br><p>How many times has the &lt;p&gt; tag been used on the page?</p>`]: `button_2`,
	[`<p>Raheem has written HTML to play an mp3 audio file of a bass line on his web page. The following code was used to embed the audio on the page.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-audio-text-3.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>source`,
	[`<p>When using the HTML &lt;title&gt; tag, where does the title actually appear?</p>`]: `button_3`,
	[`<p>Which of the following diagrams correctly identifies where the HTML &lt;p&gt; tag has been used on the web page?</p>`]: `button_2`,
	[`<p>Billy has written HTML to display the image of a golfer on his web page. The following code was used to show the image.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-image-text-3.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>src`,
	[`<p>Harry has uses an external CSS file "my-style.css" to style the HTML on a web page. Harry has written the following HTML to link the external CSS file to his web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-link-text-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>link`,
	[`<p>Which of the following HTML statements link to the external style sheet <strong><i>style.css</i></strong>?</p>`]: `button_4`,
	[`<p>Name the HTML tag used to link to external CSS files</p>`]: `>link`,
	[`<p>What is the src attribute used for within an &lt;img&gt; tag?</p>`]: `button_3`,
	[`<p>Which of the following is the least important HTML heading tag?</p>`]: `button_3`,
	[`<p>HTML has been used to produce the following web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-unordered-list-text-2-1.png"><br><br><p>The HTML is shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-unordered-list-text-2-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>li`,
	[`<p>Where on a web site should the &lt;link&gt; tag be placed?</p>`]: `button_1`,
	[`<p>Which of the following HTML statements will display a hyperlink to the file home.html?</p>`]: `button_4`,
	[`Harry clicks a hyperlink on a web page which takes him to another page on the same site. Name the type of hyperlink which Harry has clicked.`]: `>internal`,
	[`<p>Name the HTML tag used to display an image on a web page</p>`]: `>img`,
	[`<p>Which of the following diagrams correctly identifies where the HTML &lt;p&gt; tag has been used on the web page?</p>`]: `button_4`,
	[`<p>What is the alt attribute used for within an &lt;img&gt; tag?</p>`]: `button_2`,
	[`<p>What is the purpose of the HTML &lt;div&gt; tag?</p>`]: `button_3`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-audio-mc-3.png"><br><br><p>Which of the following HTML statements will embed this audio file on a web page?</p>`]: `button_3`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-video-mc-2.png"><br><br><p>Which of the following HTML statements will embed this file on a web page?</p>`]: `button_4`,
	[`<p>Name the HTML tag used to display an ordered list <strong>item</strong> on a web page</p>`]: `>li`,
	[`<p>Where, in an HTML document, should links to CSS and JavaScript files be placed?</p>`]: `button_4`,
	[`<p>What is the src attribute used for within an &lt;audio&gt; tag?</p>`]: `button_3`,
	[`<p>HTML has been used to produce the following web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-div-text-2-1.png"><br><br><p>The HTML is shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-div-text-2-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>div`,
	[`<p>Name the HTML tag used to define a paragraph</p>`]: `>p`,
	[`What on a web page is defined by the HTML &lt;p&gt; tag?`]: `>paragraph`,
	[`<p>The web page below makes use of the following HTML tags: &lt;h1&gt; &lt;h3&gt; &lt;h4&gt; &lt;p&gt; &lt;img&gt;</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-heading-mc-1.png"><br><br><p>Identify the page element which uses the &lt;h1&gt; tag.</p>`]: `button_1`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-ordered-list-mc-3.png"><br><br><p>What will be displayed on a web page using this HTML code?</p>`]: `button_1`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-unordered-list-mc-2.png"><br><br><p>Which of the following HTML statements will display this list on a web page?</p>`]: `button_3`,
	[`<p>CSS is used to style HTML as shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-div-mc-2.png"><br><br><p>Which of the following shows the resulting web page?</p>`]: `button_4`,
	[`<p>Lucy has written HTML to provide a hyperlink from a page on her website to the BBC News page. The following code was used to create the hyperlink.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-hyperlinks-2.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>href`,
	[`<p>Which of the following shows the correct structure of an HTML web page?</p>`]: `button_1`,
	[`<p>Sam has written HTML to provide a hyperlink from the home page to page 2 of his web page. The following code was used to create the hyperlink.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-hyperlinks-1.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>a`,
	[`Lily clicks a hyperlink on a web page which takes her to a webpage on a completely different website. Name the type of hyperlink which Lily has clicked.`]: `>external`,
	[`<p>Muhammad has written HTML to display a photograph of his cat Simba on his web page. The following code was used to show the image.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-image-text-4.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>alt`,
	[`<p>The web page below makes use of the following HTML tags: &lt;h1&gt; &lt;h3&gt; &lt;h4&gt; &lt;p&gt; &lt;img&gt;</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-heading-mc-2.png"><br><br><p>Identify the page element which uses the &lt;h3&gt; tag.</p>`]: `button_4`,
	[`<p>Which of the following is the HTML tag used to format a paragraph?</p>`]: `button_4`,
	[`<p>HTML has been used to produce the following web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-div-text-1-1.png"><br><br><p>The HTML is shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-div-text-1-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>div`,
	[`<p>Name the type of addressing used in this HTML example.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-mc-3.png"><br><br>`]: `button_4`,
	[`<p>HTML has been used to produce the following web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-ordered-list-text-1-1.png"><br><br><p>The HTML is shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-ordered-list-text-2-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>li`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-ordered-list-mc-2.png"><br><br><p>Which of the following HTML statements will display this list on a web page?</p>`]: `button_4`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-image-mc-3.png"><br><br><p>Which of the following HTML statements will display this picture on a web page?</p>`]: `button_1`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-unordered-list-mc-3.png"><br><br><p>What will be displayed on a web page using this HTML code?</p>`]: `button_3`,
	[`<p>Name the type of addressing used in the following HTML statement.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-mc-4.png"><br><br>`]: `button_3`,
	[`<p>Joanna adds a hyperlink to her web page using the following HTML code:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-text-2.png"><br><br><p>State the type of addressing that Joanna has used.</p>`]: `>relative`,
	[`<p>How many different heading sizes does HTML support?</p>`]: `button_2`,
	[`<p>Name the type of addressing used in the following HTML statement.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-mc-1.png"><br><br>`]: `button_2`,
	[`<p>Raheem has written HTML to play an mp4 video file of an interview with a Scottish author on his web page. The following code was used to embed the video on the page.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-video-text-2.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>type`,
	[`<p>Billy has written HTML to play an mp3 audio file of a lightning sound effect on his web page. The following code was used to embed the audio on the page.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-audio-text-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>audio`,
	[`<p>Billy has written HTML to play an mp4 video file of his band's last gig on his web page. The following code was used to embed the video on the page.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-video-text-1.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>video`,
	[`<p>Which of the following HTML statements will display a hyperlink to the site letsachieve.co.uk?</p>`]: `button_1`,
	[`<p>Sam has written HTML to display the image of a panda on her web page. The following code was used to show the image.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-image-text-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>img`,
	[`<p>Harry has uses an external CSS file "my-style.css" to style the HTML on a web page. Harry has written the following HTML to link the external CSS file to his web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-link-text-5.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>my-style`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-image-mc-1.png"><br><br><p>Which of the following HTML statements will display this picture on a web page?</p>`]: `button_3`,
	[`<p>Name the type of addressing used in this HTML example.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-mc-2.png"><br><br>`]: `button_1`,
	[`<p>Name the HTML tag used to display an ordered list on a web page</p>`]: `>ol`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-video-mc-1.png"><br><br><p>Which of the following HTML statements will embed this file on a web page?</p>`]: `button_4`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-unordered-list-mc-1.png"><br><br><p>Which of the following HTML statements will display this list on a web page?</p>`]: `button_1`,
	[`<p>Where, in an HTML document, should &lt;p&gt; and &lt;h1&gt; tags be placed?</p>`]: `button_2`,
	[`<p>Three different HTML heading tags have been used to produce the page shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-heading-text-2-1.png"><br><br><p>The following code was used to create the page.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-heading-text-2-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>h5`,
	[`Which is the most important (largest) HTML heading tag?`]: `>h1`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-image-mc-2.png"><br><br><p>Which of the following HTML statements will display this picture on a web page?</p>`]: `button_2`,
	[`<p>Which of the following is the HTML tag used to embed the file <strong><i>song.mp3</i></strong> on a web page?</p>`]: `button_1`,
	[`<p>Name the HTML tag used to display music or a sound on a web page</p>`]: `>audio`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-audio-mc-2.png"><br><br><p>Which of the following HTML statements will embed this audio file on a web page?</p>`]: `button_2`,
	[`<p>HTML has been used to produce the following web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-ordered-list-text-1-1.png"><br><br><p>The HTML is shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-ordered-list-text-1-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>ol`,
	[`<p>Nikolai adds a hyperlink to her web page using the following HTML code:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-text-4.png"><br><br><p>State the type of addressing that Nikolai has used.</p>`]: `>absolute`,
	[`<p>The web page below makes use of the following HTML tags: &lt;h1&gt; &lt;h3&gt; &lt;h4&gt; &lt;p&gt; &lt;img&gt;</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-paragraph-mc-1.png"><br><br><p>Identify the page element which uses the &lt;p&gt; tag.</p>`]: `button_3`,
	[`<p>The web page below makes use of the following HTML tags: &lt;h1&gt; &lt;h3&gt; &lt;h4&gt; &lt;p&gt; &lt;img&gt;</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-heading-mc-3.png"><br><br><p>Identify the page element which uses the &lt;h4&gt; tag.</p>`]: `button_2`,
	[`<p>The following HTML shows the basic structure of a web page. Identify the HTML tag that has been removed.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-structure-text-2.png"><br><br>`]: `>body`,
	[`<p>Name the HTML tag used to display an unordered list <strong>item</strong> on a web page</p>`]: `>li`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-hyperlinks-mc-1.png"><br><br><p>Which type of hyperlink is Services?</p>`]: `button_4`,
	[`Which HTML tag is used to define a division or a section in an HTML document?`]: `>div`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-image-mc-4.png"><br><br><p>Which of the following HTML statements will display this picture on a web page with the dimensions as shown?</p>`]: `button_4`,
	[`<p>Where, in an HTML document, should &lt;audio&gt; and &lt;video&gt; tags be placed?</p>`]: `button_4`,
	[`<p>Harry has uses an external CSS file "my-style.css" to style the HTML on a web page. Harry has written the following HTML to link the external CSS file to his web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-link-text-4.png"><br><br><p>Identify the HTML code that has been removed.</p>`]: `>stylesheet`,
	[`<img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-ordered-list-mc-1.png"><br><br><p>Which of the following HTML statements will display this list on a web page?</p>`]: `button_2`,
	[`<p>Harmony adds a hyperlink to her web page using the following HTML code:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-text-3.png"><br><br><p>State the type of addressing that Harmony has used.</p>`]: `>absolute`,
	[`<p>Harry has uses an external CSS file "my-style.css" to style the HTML on a web page. Harry has written the following HTML to link the external CSS file to his web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-link-text-3.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>head`,
	[`<p>Which of the following is the most important HTML heading tag?</p>`]: `button_2`,
	[`<p>Alice embeds an audio file on her web page using the following HTML code:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-relative-absolute-text-1.png"><br><br><p>State the type of addressing that Alice has used.</p>`]: `>relative`,
	[`<p>CSS is used to style HTML as shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-div-mc-1.png"><br><br><p>Which of the following shows the resulting web page?</p>`]: `button_2`,
	[`<p>Charlie creates the follwing HTML hyperlink.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-hyperlinks-mc-5.png"><br><p>Which of the following statements describes Charlie's hyperlink?</p>`]: `button_3`,
	[`<p>HTML has been used to produce the following web page:</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-unordered-list-text-1-1.png"><br><br><p>The HTML is shown below.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-unordered-list-text-1-2.png"><br><br><p>Identify the HTML tag that has been removed.</p>`]: `>ul`,
	[`<p>The following HTML shows the basic structure of a web page. Identify the HTML tag that has been removed.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-html-structure-text-1.png"><br><br>`]: `>head`,
	[`Which is the least important (smallest) HTML heading tag?`]: `>h6`,

	// Implementation (Javascript)
	[`<p>When the mouse pointer moves over the word Hello on this web page, the word changes colour and becomes Goodbye.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-javascript-mouseover-mouseout-mc-3.png"><br><p>Which JavaScript event has been used?</p>`]: `button_4`,
	[`<p>When the mouse pointer moves away from the word Goodbye on this web page, the word changes colour and becomes Hello.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-javascript-mouseover-mouseout-mc-4.png"><br><p>Which JavaScript event has been used?</p>`]: `button_2`,
	[`<p>When the mouse pointer moves over the image of a tiger on this web page, it changes to the picture of a lion.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-javascript-mouseover-mouseout-mc-5.png"><br><p>Which type of coding has been used?</p>`]: `button_3`,
	[`<p>Kevyn has developed a web page to share football training tips. The page has several images. When the mouse pointer rolls over an image, the image doubles in size. When the mouse pointer rolls away from the image again, the image returns to its normal size.</p><p>State the name of the event that has been used to implement the image returning to its normal size.</p>`]: `>onmouseout`,
	[`<p>When the mouse pointer moves away from the multicoloured word on this web page, the text becomes black.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-javascript-mouseover-mouseout-mc-6.png"><br><p>Which type of coding has been used?</p>`]: `button_2`,
	[`<p>Lori has developed a web page to showcase a dress that she has designed. When the mouse pointer hovers over the image of the dress, the image changes to show how the dress looks from the back.</p><p>State the type of coding that Lori has used to implement this.</p>`]: `>javascript`,
	[`<p>When the mouse pointer moves away from the image of a zebra on this web page, the image decreases in size.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-javascript-mouseover-mouseout-mc-2.png"><br><p>Which JavaScript event has been used?</p>`]: `button_1`,
	[`<p>When the mouse pointer moves over the image of a zebra on this web page, the image increases in size.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-javascript-mouseover-mouseout-mc-1.png"><br><p>Which JavaScript event has been used?</p>`]: `button_3`,
	[`<p>Abi has developed a web page to share information about her new puppy called Cookie. When the mouse pointer hovers over an image of Cookie, the image changes to a different picture of him.</p><p>State the name of the event that Abi has used to implement this.</p>`]: `>onmouseover`,

	// Testing (web)
	[`<p>Which of the following should be tested in terms of consistency on a web page?</p><ol><li>Navigation</li><li>Layout</li><li>CSS id names</li><li>Paragraph length</li></ol>`]: `button_1`,
	[`<p>The website below was tested.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-testing-mc-6.png"><br><p>Why did it fail?</p>`]: `button_4`,
	[`<p>The website below was tested.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-testing-mc-8.png"><br><p>Why did it fail?</p>`]: `button_4`,
	[`<p>Which of the following would <strong>NOT</strong> be involved when testing a web page?</p>`]: `button_3`,
	[`<p>The website below was tested.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-testing-mc-7.png"><br><p>Why did it fail?</p>`]: `button_2`,
	[`<p>Which of the following should be checked when testing a web page?</p><ol><li>Web pages match the user-interface design</li><li>All HTML is commented</li><li>All image files are .png or .jpg</li><li>All links and navigation work correctly</li></ol>`]: `button_3`,
	[`<p>Which of the following should be tested in terms of consistency on a web page?</p><ol><li>Fonts</li><li>Text size</li><li>Colours</li><li>Sentence length</li></ol>`]: `button_3`,
	[`<p>Which of the following should be checked when testing a web page?</p><ol><li>All heading sizes h1 to h6 are used</li><li>All text, graphics and video display correctly</li><li>Pages are consistent in terms of fonts, layout and colours</li><li>All audio files are under 5 minutes in length</li></ol>`]: `button_1`,

	// Evaluation (web)
	[`<p>Wagtail Dog Walking Services have designed a new website. During the analysis stage it was agreed that the site should have a link from the Home page to a Book Now page to let customers book their dog in for a walk, and a link to a Contact page. Other than these links, the Home page should show only the name of the company and photographs of dogs.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-fitness-for-purpose-mc-4.png"><br><p>Which of the following is true?</p>`]: `button_2`,
	[`<p>Duncastle United Football Club have designed a new website. During the analysis stage it was agreed that the home page should provide a brief history of the club with an image of the stadium, and provide links to player information and the club shop where supporters can be purchase replica kits and other items.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-fitness-for-purpose-mc-2.png"><br><p>Which of the following is true?</p>`]: `button_1`,
	[`<p>Greenhouse Gardening Services have designed a new website. During the analysis stage it was agreed that the site should include an online shop to allow customers to buy plants and flowers by clicking the Buy Now button on any product page. Each product page should also include the product name, description, image and price.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-fitness-for-purpose-mc-6.png"><br><p>Which of the following is true?</p>`]: `button_1`,
	[`<p>Duncastle United Football Club have designed a new website. During the analysis stage it was agreed that the home page should provide a brief history of the club with an image of the stadium, and provide links to player information and the club shop where supporters can be purchase replica kits and other items.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-fitness-for-purpose-mc-3.png"><br><p>Which of the following is true?</p>`]: `button_2`,
	[`<p>Greenhouse Gardening Services have designed a new website. During the analysis stage it was agreed that the site should include an online shop to allow customers to buy plants and flowers by clicking the Buy Now button on any product page. Each product page should also include the product name, description, image and price.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-fitness-for-purpose-mc-7.png"><br><p>Which of the following is true?</p>`]: `button_2`,
	[`<p>Wagtail Dog Walking Services have designed a new website. During the analysis stage it was agreed that the site should have a link from the Home page to a Book Now page to let customers book their dog in for a walk, and a link to a Contact page. Other than these links, the Home page should show only the name of the company and photographs of dogs.</p><img class="img-fluid" src="https://hashtag-achieve.s3.amazonaws.com/static/images/questions/computing-science/n5-wdd-fitness-for-purpose-mc-5.png"><br><p>Which of the following is true?</p>`]: `button_1`,
	[`During evaluation, a website is said to be fit for purpose if:`]: `button_2`,
};

function toggleAutoAnswer() {
    GM_setValue('autoAnswer', !GM_getValue('autoAnswer', false));
    document.getElementById("autoAnswerButton").innerText = "Auto Answer " + (GM_getValue('autoAnswer', false) ? 'ON' : 'OFF');
    setTimeout(() => {
        document.getElementById("navbarSettings").click();
    }, 100);
};

document.body.onload = answer;
function answer() {
    const settings = document.getElementById("navbarSettings").parentElement.querySelector(".dropdown-menu");
    const btn = document.createElement("button");
    const txt = document.createTextNode("Auto Answer " + (GM_getValue('autoAnswer', false) ? 'ON' : 'OFF'));
    btn.appendChild(txt);
    btn.onclick = toggleAutoAnswer;
    btn.style.cssText = `border: none; width: 100%; height: 100%;`;
    btn.id = "autoAnswerButton";
    settings.appendChild(btn);

    const question = document.querySelector(".card-header.question-card-header.pt-4.pb-4.border-secondary > .row.m-0 > .col").innerHTML.trim();
    if (data[question].charAt(0) === ">") {
        document.getElementById('text-answer').value = data[question].slice(1);
        if (GM_getValue('autoAnswer', false)) {
            setTimeout(() => {
                document.getElementById("submit-answer-button").click();
            }, 500);
        }
    } else {
        const answer = document.getElementById(data[question]);
        console.log(answer);
        if (GM_getValue('autoAnswer', false)) {
            setTimeout(() => {
                answer.click();
            }, 500);
        } else {
            answer.style.cssText = `background-color: #5787AE !important;`
        }
    }
};
